version: '3'

services:
  krakend:
    image: devopsfaith/krakend
    labels:
      traefik.backend: 'krakend'
      traefik.frontend.rule: 'PathPrefix: /'
      traefik.enable: 'true'
      traefik.port: '8080'
    container_name: krakend
    restart: always
    environment: 
      KRAKEND_CONFIG: krakend.json
    volumes:
      - ./conf:/etc/krakend
    networks:
     traefik:
       ipv4_address: 172.40.0.5
    ports:
      - 8081:8080
      - 8090:8090
      - 9091:9091

  check:
    image: devopsfaith/krakend
    working_dir: /etc/krakend/
    command: check -c krakend.json
    volumes: 
      - ./conf:/etc/krakend

  app2:
      hostname: app2
      build:
        context: ./stack/node_backend
        dockerfile: Dockerfile
      labels:
        traefik.backend: 'app-2'
        traefik.frontend.rule: 'Host: kraken.perro ,PathStrip: /api/app2/'
        traefik.enable: 'true'
        traefik.port: '80'
      networks:
       traefik:
        ipv4_address: 172.40.0.21

networks:
 traefik:
  driver: bridge
  ipam:
    config:
    - subnet: 172.40.0.0/24
